name: build Medusa Backend

on:
  push:
    branches:
      - cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY_NAME: medusa


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
        

      - name: Terraform Destroy
        if: always()
        run: |
          cd terraform
          terraform destroy -auto-approve